# Generated by Django 6.0.3 on 2026-03-16 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("url", models.URLField(unique=True)),
                ("source", models.CharField(max_length=100)),
                ("summary", models.TextField(blank=True, null=True)),
                ("sentiment_score", models.FloatField(default=0.0)),
                ("sentiment_label", models.CharField(default="Neutral", max_length=20)),
                ("published_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-published_at"],
            },
        ),
    ]
