# Generated by Django 6.0.3 on 2026-03-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news_aggregator", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={},
        ),
        migrations.RemoveField(
            model_name="article",
            name="sentiment_score",
        ),
        migrations.AddField(
            model_name="article",
            name="analysis_detail",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="category",
            field=models.CharField(
                choices=[
                    ("MED", "Medicina"),
                    ("POL", "Política"),
                    ("TEC", "Tecnología"),
                    ("ECO", "Economía"),
                    ("CRP", "Criptomonedas"),
                ],
                default="TEC",
                max_length=3,
            ),
        ),
    ]
