# Generated by Django 6.0.3 on 2026-03-16 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "news_aggregator",
            "0002_alter_article_options_remove_article_sentiment_score_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="category",
            field=models.CharField(
                choices=[
                    ("MED", "Medicina"),
                    ("POL", "Política"),
                    ("TEC", "Tecnología"),
                    ("ECO", "Economía"),
                    ("CRP", "Criptomonedas"),
                    ("CYB", "Ciberseguridad"),
                ],
                default="TEC",
                max_length=3,
            ),
        ),
    ]
